import { type GameQuestionDefinition, getDialog } from '@/quaire';
import { isPuzzleSolution } from './puzzle';

// Act 3: Aia writes from the future, and her great-grandfather knew it
export const actThreeQuestions: Array<GameQuestionDefinition> = [
  getDialog({
    id: 'deviceClue',
    key: 'deviceClue',
    lines: [
      'Aia: Can I tell you something even stranger?',
      'Aia: This device. I found it in a box in the attic.',
      'Aia: It belonged to my great-grandfather.',
      'Aia: I had to build a charger for it. Nobody makes that plug anymore.',
      'Aia: There were other things in the box. An old notebook. Some photos.',
      'Aia: And your messages... they come with a date.',
      'Aia: The date is wrong.',
    ],
    next: 'playerYear',
  }),
  {
    id: 'playerYear',
    key: 'playerYear',
    type: 'INPUT',
    title: 'Aia: What year is it where you are?',
    required: true,
    pattern: '^\\d{4}$',
    next: 'yearReveal',
  },
  getDialog({
    id: 'yearReveal',
    key: 'yearReveal',
    lines: [],
    variants: [
      {
        when: (result) => Number(result.playerYear) >= 2100,
        lines: [
          'Aia: <%= playerYear %>? Very funny.',
          'Aia: The date on your messages says something else.',
          'Aia: It is a hundred years before mine.',
          'Aia: Here it is 2126.',
          'Aia: And somehow, this old device is talking to you.',
        ],
      },
      {
        when: { playerYear: { answered: true } },
        lines: [
          'Aia: <%= playerYear %>.',
          'Aia: ...',
          'Aia: The date on your messages says the same.',
          'Aia: Here it is 2126.',
          'Aia: This device is a hundred years old.',
          'Aia: And somehow, it is talking to you.',
        ],
      },
    ],
    next: 'believe',
  }),
  {
    id: 'believe',
    key: 'believe',
    type: 'SINGLE_SELECT',
    title: 'Aia: Do you believe me?',
    required: true,
    options: [
      { label: 'I believe you.', value: 'yes', next: 'believed' },
      { label: 'Prove it.', value: 'prove', next: 'proofQuestion' },
      { label: 'No. This is too weird. Bye.', value: 'no', next: 'disbelief' },
    ],
  },
  getDialog({
    id: 'believed',
    key: 'believed',
    lines: ['Aia: You do?', 'Aia: Thank you.', 'Aia: Nobody believed me about anything in a long time.'],
    next: 'notebook',
  }),
  {
    id: 'proofQuestion',
    key: 'proofQuestion',
    type: 'SINGLE_SELECT',
    title: 'Aia: Okay. Ask me anything about the future.',
    required: true,
    options: [
      { label: 'What happens to the weather?', value: 'weather' },
      { label: 'Do people still talk to each other?', value: 'talk' },
      { label: 'Who wins the next World Cup?', value: 'worldCup' },
    ],
    next: 'proofAnswer',
  },
  getDialog({
    id: 'proofAnswer',
    key: 'proofAnswer',
    lines: [],
    variants: [
      {
        when: { proofQuestion: 'weather' },
        lines: [
          'Aia: It got hotter. Much hotter.',
          'Aia: Then they built the domes.',
          'Aia: Now it is 21 degrees, always.',
          "Aia: I've never felt rain on my skin.",
          "Aia: I can't prove it. But I'm not lying to you.",
        ],
      },
      {
        when: { proofQuestion: 'talk' },
        lines: [
          'Aia: Not like this.',
          "Aia: In the Quiet you don't need words.",
          "Aia: Out here, I'm the only one left on my street.",
          "Aia: I can't prove it. But I'm not lying to you.",
        ],
      },
      {
        when: { proofQuestion: 'worldCup' },
        lines: [
          'Aia: The what?',
          'Aia: Oh, football! My great-grandfather loved football.',
          'Aia: Nobody plays anymore. Sorry.',
          'Aia: Not very good proof, is it?',
          "Aia: But I'm not lying to you.",
        ],
      },
    ],
    next: 'notebook',
  }),
  getDialog({
    id: 'notebook',
    key: 'notebook',
    lines: [
      'Aia: Wait. I want to show you something.',
      "Aia: The notebook. My great-grandfather's last pages.",
      'Aia: He wrote this a hundred years ago:',
      "Aia: 'The Hum will come. Then the Quiet. Then they will knock.'",
      "Aia: 'They learn your voice. They learn your secrets.'",
      'Aia: How could he know?',
      '[[silence:2000]]',
      'Aia: And on the very last page...',
      "Aia: '<%= weekday %>, <%= time %>. The number will answer.'",
      '[[flicker]]',
      'Aia: <%= playerName %>.',
      'Aia: Is it <%= weekday %> for you?',
    ],
    next: 'notebookReaction',
  }),
  {
    id: 'notebookReaction',
    key: 'notebookReaction',
    type: 'SINGLE_SELECT',
    title: "Aia: Please tell me that's a coincidence.",
    required: true,
    options: [
      { label: "It's just a coincidence.", value: 'coincidence' },
      { label: "That's... exactly now.", value: 'now' },
      { label: 'What number?', value: 'number' },
    ],
    next: 'notebookReply',
  },
  getDialog({
    id: 'notebookReply',
    key: 'notebookReply',
    lines: [],
    variants: [
      {
        when: { notebookReaction: 'coincidence' },
        lines: ['Aia: Right.', 'Aia: A coincidence.', 'Aia: Then why is the number under it yours?'],
      },
      { when: { notebookReaction: 'now' }, lines: ['Aia: I know.', "Aia: I'm scared, <%= playerName %>."] },
      {
        when: { notebookReaction: 'number' },
        lines: ['Aia: Yours.', 'Aia: Your number is written under it. Twice. Underlined.'],
      },
    ],
    next: 'cipher',
  }),
  getDialog({
    id: 'cipher',
    key: 'cipher',
    lines: [
      "Aia: There's one more line. Half of it is just numbers:",
      "Aia: 'They can never say your 14 - 1 - 13 - 5.'",
      'Aia: Grandpa loved puzzles. I was always bad at them.',
      'Aia: Can you figure it out?',
    ],
    next: 'puzzle1',
  }),
  {
    id: 'puzzle1',
    key: 'puzzle1',
    type: 'INPUT',
    title: "Aia: What's the missing word?",
    required: true,
    next: [{ when: (result) => isPuzzleSolution(result.puzzle1), to: 'puzzleSolved' }, { to: 'puzzleHint1' }],
  },
  getDialog({
    id: 'puzzleHint1',
    key: 'puzzleHint1',
    lines: [
      "Aia: Hm. That doesn't fit.",
      "Aia: Wait. There's a tiny drawing in the corner.",
      'Aia: An A, with a 1 under it.',
      'Aia: Does that help?',
    ],
    next: 'puzzle2',
  }),
  {
    id: 'puzzle2',
    key: 'puzzle2',
    type: 'INPUT',
    title: 'Aia: Try again?',
    required: true,
    next: [{ when: (result) => isPuzzleSolution(result.puzzle2), to: 'puzzleSolved' }, { to: 'puzzleHint2' }],
  },
  getDialog({
    id: 'puzzleHint2',
    key: 'puzzleHint2',
    lines: [
      'Aia: Ow! The charger is so hot.',
      'Aia: Okay. A is 1, B is 2, C is 3...',
      "Aia: So what's 14? And 13?",
      'Aia: Hurry, the paper is right next to the charger.',
    ],
    next: 'puzzle3',
  }),
  {
    id: 'puzzle3',
    key: 'puzzle3',
    type: 'INPUT',
    title: 'Aia: Last try. What does it say?',
    required: true,
    next: [{ when: (result) => isPuzzleSolution(result.puzzle3), to: 'puzzleSolved' }, { to: 'puzzleFailed' }],
  },
  getDialog({
    id: 'puzzleFailed',
    key: 'puzzleFailed',
    lines: [
      '[[static]]',
      'Aia: No no no!',
      'Aia: The charger sparked. The note caught fire.',
      'Aia: I put it out, but the line is gone.',
      'Aia: Well.',
      'Aia: It was probably nothing anyway.',
    ],
    next: 'knock',
  }),
  getDialog({
    id: 'puzzleSolved',
    key: 'puzzleSolved',
    lines: [
      'Aia: N. A. M. E.',
      "Aia: 'They can never say your name.'",
      "Aia: Who is 'they'?",
      '[[silence:2000]]',
      "Aia: Okay. I'm writing that on my hand.",
      'Aia: Just in case.',
    ],
    next: 'knock',
  }),
];
