import { type GameQuestionDefinition, getDialog } from '@/quaire';

const taken = [
  'Aia: Mila!',
  "Aia: She's so cold.",
  "Aia: She's hugging me. She won't let go.",
  'Aia: Her eyes. Why are her eyes so',
  '[[static]]',
  "Aia: it's not her it's not her it's",
  '[Connection lost.]',
  '[[silence:5000]]',
  '[1 new message from: Aia]',
  '!!Aia: hi.',
  '!!Aia: everything is fine now.',
  "!!Aia: it's warm here. you should come.",
  '!!Aia: what is your address?',
];

export const endingQuestions: Array<GameQuestionDefinition> = [
  getDialog({
    id: 'blocked',
    key: 'blocked',
    lines: [
      '[You blocked the number.]',
      '[You put the phone away.]',
      '[[silence:3000]]',
      '[[static]]',
      '[1 new message from: Mila]',
      '!!Mila: she was so lonely.',
      '!!Mila: she is not lonely anymore.',
    ],
    end: 'THE END',
  }),
  getDialog({
    id: 'disbelief',
    key: 'disbelief',
    lines: [
      'Aia: Okay.',
      "Aia: I understand. I wouldn't believe me either.",
      'Aia: Thank you for talking to me anyway, <%= playerName %>.',
      '[Aia is offline.]',
      '[[silence:4000]]',
      '[1 new message from: Aia]',
      '!!Aia: someone is knocking',
    ],
    end: 'THE END',
  }),
  getDialog({
    id: 'doorOpens',
    key: 'doorOpens',
    lines: taken,
    variants: [
      {
        when: { finalDoor: 'tooLate' },
        lines: ["Aia: You're not answering.", "Aia: I'm opening it.", ...taken],
      },
    ],
    end: 'THE END',
  }),
  getDialog({
    id: 'frozen',
    key: 'frozen',
    lines: [
      'Aia: <%= playerName %>??',
      'Aia: Where do I go??',
      '[[knock]]',
      '[[knock]]',
      "Aia: The back door. It's open.",
      'Aia: Someone is in the kitchen.',
      'Aia: Mrs. Okafor is smiling at me. Her mouth is',
      '[[static]]',
      '[Connection lost.]',
    ],
    end: 'THE END',
  }),
  getDialog({
    id: 'outside',
    key: 'outside',
    lines: [
      'Aia: Okay. Okay. Running.',
      "Aia: I'm outside!",
      'Aia: The air is warm. 21 degrees, of course.',
      "Aia: They're coming around the house. I can hear them.",
      'Aia: Wait.',
      "Aia: There's a light across the street.",
      "Aia: Someone is at the window. They're holding up a sign.",
      'Aia: It says: SAY YOUR NAME.',
      '[[silence:2000]]',
      "Aia: I'm shouting it. AIA!",
      "Aia: They're shouting back. JONAH!",
      "Aia: They can say names. They're real. They're REAL.",
      "Aia: Thank you, <%= playerName %>. I'll tell Jonah about you.",
      '[Aia is offline.]',
    ],
    end: 'THE END ... OR A BEGINNING?',
  }),
  getDialog({
    id: 'tooAfraid',
    key: 'tooAfraid',
    lines: [
      'Aia: Run?',
      "Aia: I... I can't. My legs won't move.",
      "Aia: What if there's no one out there?",
      "Aia: What if it's just me and them?",
      '[[knock]]',
      'Aia: I should have trusted you more.',
      'Aia: The front door is opening.',
      'Aia: why is it so warm',
      '[Connection lost.]',
    ],
    end: 'THE END',
  }),
  getDialog({
    id: 'survived',
    key: 'survived',
    lines: [
      "Aia: It's you.",
      "Aia: It's really you.",
      'Aia: I found new batteries in the attic. Grandpa kept a whole box of them.',
      'Aia: I think he knew.',
      'Aia: Talk tomorrow, <%= playerName %>? Same time. <%= time %>.',
    ],
    end: 'THE END ... FOR NOW',
  }),
  getDialog({
    id: 'notHer',
    key: 'notHer',
    lines: ['Aia: ...', '[[static]]', '!!Aia: wrong.', '!!Aia: are you one of them now?', '[Aia is offline.]'],
    end: 'THE END',
  }),
  getDialog({
    id: 'goodbyeEnd',
    key: 'goodbyeEnd',
    lines: [],
    variants: [
      {
        when: { rememberHer: 'always' },
        lines: [
          "Aia: Then I'm not really gone.",
          'Aia: Goodbye, <%= playerName %>.',
          '[Aia went into the Quiet.]',
          '[[silence:4000]]',
          '[[static]]',
          '!!Aia: it is so warm here.',
          '!!Aia: we remember you.',
        ],
      },
      {
        when: { rememberHer: 'try' },
        lines: [
          "Aia: That's enough.",
          'Aia: Nobody remembers anything in there anyway.',
          'Aia: Goodbye, <%= playerName %>.',
          '[Aia went into the Quiet.]',
          '[[silence:4000]]',
          '!!Aia: come and find us.',
        ],
      },
    ],
    end: 'THE END',
  }),
];
